# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:49
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, default='', verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_keywords',
            field=models.TextField(blank=True, default='', verbose_name='SEO keywords'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Краткое описание'),
        ),
    ]
