# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20160501_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
    ]
