# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 21:55
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20160501_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Краткое описание'),
        ),
    ]
