# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 18:48
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import meta.models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug_category', models.SlugField()),
                ('sort_in_menu', models.CharField(default='', max_length=255, verbose_name='Сортировка меню')),
                ('type_menu', models.CharField(choices=[('p', 'Страница'), ('c', 'Категория')], default='', max_length=1)),
                ('meta_keywords', models.TextField(blank=True, default='', verbose_name='SEO keywords')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='SEO description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Category')),
            ],
            options={
                'db_table': 'categorys',
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('meta_keywords', models.TextField(blank=True, default='', verbose_name='SEO keywords')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='SEO description')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Содержание страницы')),
            ],
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('meta_keywords', models.TextField(blank=True, default='', verbose_name='SEO keywords')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='SEO description')),
            ],
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
