# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_category_page_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(default='', to='engine.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(default='', to='engine.Tag'),
        ),
    ]
