# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20160503_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeAriticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_likes', models.IntegerField(default=0)),
                ('ip', models.CharField(max_length=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Article')),
            ],
            options={
                'db_table': 'likeandarticle',
                'ordering': ['-article'],
            },
        ),
    ]
