# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_likeariticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
